language: php

php:
  - 5.3
  - 5.5

cache:
  directories:
    - "$HOME/.composer/cache/files"

before_install:
  - composer self-update

install: true

# http://docs.travis-ci.com/user/migrating-from-legacy/#tl%3Bdr
sudo: false
