language: php

php:
  - 5.3
  - 5.5

matrix:
  allow-failures:
    - php: 5.3

branches:
  except:
    - master

branches:
  only:
    - /^dev-.+$/

install: true

# http://docs.travis-ci.com/user/migrating-from-legacy/#tl%3Bdr
sudo: false

notifications:
  slack:
    - secure: WXkspu3HHy2S0yQZykAKIxEcPBpG3pPLNvdatBfA4lJ0mhXu6XYzGjmqgQBXxAzO+1XfzOcT7JtordzCk8LDd2rOzxhCxR6o4Jpyhi3Qoiqf+d8CsPmMAxeldiiqEUCIY9UouRq7WPuN2G4q0qXXJ763qOK+Jd1/lxiZW3TetUSN5w1f+Riz1gUX6nu7vxGiZdBdZ7AhMun93mAkeKHUc9XOEOlGb2W3CQl7ZEcC3KlwcdYqky6p+m4FWmmyrVEQWPMkUoHYKdnLWyiDMPjbD0GlFjsE+owVMQmjBMX8btaRAdzIg3r/FkFPuWZY4S4IfMWQIK4l9sWiqnWOvAgsjU+tQ0EtjHhl3s581Y5/jIs/aDvQxV6aMEmbehpXMkw0ANPwb5g/xLb7rih9s7ZDvhe3wWAIhbyB2klRGWCsKVlbiKTA9zS0X+zpLHecFYZN6d9CdCwNLJQhXeyamahfXRAOD7PysFv7fcDrLhWKeqOjTT7Gyzk2nHpbIXqaZlSwyBFj6YeDQTpveRaWsqztOWo7ycgx5cEBvK3iDL+Ysoe7mLnLYsZGDqADWcWPVQWp+g+LvfbXG/ugwIe7CPk8QY6rFgbRadWTsE8RJKfULvRuCyDS308Q9hfkCjmDqXA/pHybrujgkwZMojJ8h/GVuzowc6cAhFwyHtv0/gD9HGA=
