language: php

php:
  - 5.3
  - 5.5

cache:
  directories:
    - "$HOME/.composer/cache/files"

before_script:
  - git config --global credential.helper 'cache --timeout=3600'
  - git config --global user.email "$(git log --format="%ce" -n 1 | tr -d '\n' | tr -d ' ')"
  - git config --global user.name "$(git log --format="%cn" -n 1 | tr -d '\n')"
  - git config --global push.default simple

script:
  - ./travis.sh

# http://docs.travis-ci.com/user/migrating-from-legacy/#tl%3Bdr
sudo: false
